<a href="https://colab.research.google.com/github/PallaviSundar/AIML-Programs/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### numpy array

In [ ]:
import numpy as np
cities=np.array(['delhi','mumbai','hydarabad','chennai'])
solar_energy=np.array([100,30,50,39])
wind_energy=np.array([105,300,500,678])
print(cities)

['delhi' 'mumbai' 'hydarabad' 'chennai']


In [ ]:
print(solar_energy)

[100  30  50  39]


In [ ]:
print(wind_energy)

[105 300 500 678]


### **1.array** creation

In [ ]:
a=np.array([1,2,3])
b=np.zeros(3)
c=np.ones((2,2))
d=np.arange(0,10,2)
e=np.linspace(0,1,5)
f=np.random.rand(3)

In [ ]:
print(a)

[1 2 3]


In [ ]:
print(b)

[0. 0. 0.]


In [ ]:
print(c)

[[1. 1.]
 [1. 1.]]


In [ ]:
print(d)

[0 2 4 6 8]


In [ ]:
print(e)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
print(f)

[0.61137705 0.18842677 0.57892292]


In [ ]:
f=np.random.randint(3)
print(f)

2


#### array attributes

In [ ]:
print("Shape:",solar_energy.shape)
print("Datatype:",solar_energy.dtype)
print("Dimension:",solar_energy.ndim)


Shape: (4,)
Datatype: int64
Dimension: 1


#### indexing and slicing

In [ ]:
print(cities[0])

delhi


In [ ]:
print(solar_energy[0:3])

[100  30  50]


In [ ]:
print(solar_energy[-3::])

[30 50 39]


In [ ]:
print(wind_energy[1:4])

[300 500 678]


In [ ]:
print(wind_energy[-3::])

[300 500 678]


In [ ]:
print(wind_energy[0::2])

[105 500]


#### arthemetic operation in numeric python

In [ ]:
total_energy=solar_energy+wind_energy
dif_energy=solar_energy-wind_energy
energy_sqared=solar_energy**2

In [ ]:
print("total_energy:",total_energy)
print("diffence in energy:",dif_energy)
print("squared solar:",energy_sqared)

total_energy: [205 330 550 717]
diffence in energy: [  -5 -270 -450 -639]
squared solar: [10000   900  2500  1521]


In [ ]:
print("mean(solar):",np.mean(solar_energy))
print("median(wind):",np.median(wind_energy))
print("Standard Deviation(total):",np.std(total_energy))
print("variance(total):",np.var(total_energy))
print("minimum(solar):",np.min(solar_energy))
print("maximum(solar):",np.max(solar_energy))

mean(solar): 54.75
median(wind): 400.0
Standard Deviation(total): 197.30243282838657
variance(total): 38928.25
minimum(solar): 30
maximum(solar): 100


#### reshape and Traspose

In [ ]:
energy_matrix=np.array([solar_energy,wind_energy])
print("original matrix:\n",energy_matrix)

original matrix:
 [[100  30  50  39]
 [105 300 500 678]]


In [ ]:
print(energy_matrix.T)

[[100 105]
 [ 30 300]
 [ 50 500]
 [ 39 678]]


#### boolean indexing

In [ ]:
print("cities whith solar > 20:",cities[solar_energy > 20])

cities whith solar > 20: ['delhi' 'mumbai' 'hydarabad' 'chennai']


#### aggregate functions

In [ ]:
print("total solar energy:",np.sum(solar_energy))
print("product of wind energy:",np.prod(wind_energy))
print("cumulative sum (solar):",np.cumsum(solar_energy))


total solar energy: 219
product of wind energy: 10678500000
cumulative sum (solar): [100 130 180 219]


#### mathemetical functions

In [ ]:
print("square root(solar)",np.sqrt(solar_energy))
print("exponential(wind)",np.exp(wind_energy//100))


square root(solar) [10.          5.47722558  7.07106781  6.244998  ]
exponential(wind) [  2.71828183  20.08553692 148.4131591  403.42879349]


In [ ]:
print("Sorted total energy:",np.sort(total_energy))
print("Index of max solar:",np.argmax(solar_energy))
print("Index of min wind:",np.argmin(wind_energy))


Sorted total energy: [205 330 550 717]
Index of max solar: 0
Index of min wind: 0


#### stacking arrays

In [ ]:
v_stack=np.vstack((solar_energy,wind_energy))
h_stack=np.hstack((solar_energy,wind_energy))
print("vertical stack:\n",v_stack)

vertical stack:
 [[100  30  50  39]
 [105 300 500 678]]


In [ ]:
w1=np.arange(12).reshape(3,4)
w2=np.arange(12,24).reshape(3,4)
print(w1)
print(w2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
np.hstack((w1,w2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
np.vstack((w1,w2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### broadcasting

In [ ]:
increased_solar=solar_energy*1.1
print("solar energy incresed by 10%:",increased_solar)

solar energy incresed by 10%: [110.   33.   55.   42.9]
